<?php

return [
    'Hà Nội',
    'Hải Phòng',
    'Quảng Ninh',
    'Cao Bằng',
    'Lạng Sơn',
    'Lào Cai',
    'Tuyên Quang',
    'Điện Biên',
    'Lai Châu',
    'Sơn La',
    'Phú Thọ',
    'Ninh Bình',
    'Thanh Hóa',
    'Nghệ An',
    'Huế',
    'Quảng Trị',
    'Đà Nẵng',
    'Quảng Ngãi',
    'Gia Lai',
    'Đắk Lắk',
    'Lâm Đồng',
    'Khánh Hòa',
    'Thành phố Hồ Chí Minh',
    'Cần Thơ',
    'An Giang',
    'Đồng Tháp',
    'Cà Mau',
];